"""Archive project files without credentials, environments or generated bytecode.

Each byte stream is hashed as it is written, and source metadata is checked
before/after reading. This is a data transfer snapshot, not a running-process
checkpoint. Run only after checking that project calculations are stopped.
"""
import argparse, hashlib, io, json, os, re, tarfile
from pathlib import Path
from datetime import datetime, timezone

EXCLUDED_PARTS = {'.git', '.venv', '__pycache__', '.pytest_cache'}
EXCLUDED_TREES = ('outputs/li_symbolic_dependencies', 'outputs/paper_metric_reference/python_deps')
SECRET = re.compile(rb'-----BEGIN (?:RSA |EC |OPENSSH )?PRIVATE KEY-----|gh[pousr]_[A-Za-z0-9]{30,}|github_pat_[A-Za-z0-9_]{40,}')
class HashReader:
    def __init__(self, stream): self.stream=stream; self.hash=hashlib.sha256()
    def read(self, size=-1):
        data=self.stream.read(size); self.hash.update(data); return data

def main():
    ap=argparse.ArgumentParser(); ap.add_argument('source',type=Path); ap.add_argument('archive',type=Path)
    args=ap.parse_args(); root=args.source.resolve(); output=args.archive.resolve()
    if output.is_relative_to(root): raise ValueError('Archive must be outside source tree')
    if output.exists(): raise FileExistsError(output)
    output.parent.mkdir(parents=True,exist_ok=True)
    records=[]; omitted=[]
    with tarfile.open(output,'w:gz',compresslevel=4) as tar:
        for folder,dirs,names in os.walk(root):
            for name in list(dirs):
                path=Path(folder)/name; rel=path.relative_to(root).as_posix()
                if name in EXCLUDED_PARTS or name.endswith('.egg-info') or rel in EXCLUDED_TREES or path.is_symlink():
                    dirs.remove(name); omitted.append(rel+'/')
            dirs.sort()
            for name in sorted(names):
                path=Path(folder)/name; rel=path.relative_to(root).as_posix()
                if name.endswith('.pyc') or path.is_symlink(): omitted.append(rel); continue
                if name=='.env' or name.startswith(('.env.','id_rsa','id_ed25519')): raise ValueError('Review sensitive filename: '+rel)
                if rel=='MIGRATION_FILES.json': raise ValueError('Reserved manifest name')
                before=path.stat()
                if path.suffix.lower() in {'.py','.md','.json','.txt','.toml','.yaml','.yml','.sh','.ps1','.ini','.cfg','.log','.xml','.wls','.wl'} and before.st_size < 16000000:
                    if SECRET.search(path.read_bytes()): raise ValueError('Review potential credential: '+rel)
                info=tar.gettarinfo(str(path),arcname=rel);info.uid=info.gid=0;info.uname=info.gname=''
                with path.open('rb') as stream:
                    reader=HashReader(stream);tar.addfile(info,reader)
                after=path.stat()
                if (before.st_size,before.st_mtime_ns)!=(after.st_size,after.st_mtime_ns): raise RuntimeError('Source changed: '+rel)
                records.append({'path':rel,'size':before.st_size,'sha256':reader.hash.hexdigest()})
        manifest={'created_utc':datetime.now(timezone.utc).isoformat(),'files':records,'omitted':omitted,'excluded_installations':list(EXCLUDED_TREES),'note':'Processes and OS/application installations are not copied; see migration handoff.'}
        raw=json.dumps(manifest,ensure_ascii=False,indent=2).encode();info=tarfile.TarInfo('MIGRATION_FILES.json');info.size=len(raw);tar.addfile(info,io.BytesIO(raw))
    h=hashlib.sha256()
    with output.open('rb') as f:
        for chunk in iter(lambda:f.read(1024*1024),b''):h.update(chunk)
    summary={'asset':output.name,'bytes':output.stat().st_size,'sha256':h.hexdigest(),'file_count':len(records),'uncompressed_bytes':sum(r['size'] for r in records),'omitted':omitted}
    output.with_suffix(output.suffix+'.json').write_text(json.dumps(summary,ensure_ascii=False,indent=2)+'\n')
    print(json.dumps({k:v for k,v in summary.items() if k!='omitted'}),flush=True)
if __name__=='__main__':main()
