"""Fresh three-node actual-source check of the historical Fig.5 scalar22 input."""
import hashlib,json,os,time
from concurrent.futures import ProcessPoolExecutor,as_completed
from pathlib import Path
import numpy as np
ROOT=Path(__file__).resolve().parents[1];FOLDER=ROOT/'docs/environment_reproduction'
NAME='forced_mode_nr8_nt18_L18_alpha0.3_rp41.6_mg1_sl2_gh0.0001_go32000_coulomb_inner0.0005_outer320_log_h32.json'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def pair(z):return [float(z.real),float(z.imag)]
def worker(payload):
 from environment_source import ThresholdCloud,project_source
 from environment_lorenz_mode import LorenzMetricMode
 from environment_dense_metric import configure_metric_backend
 from source_provenance import source_fingerprint
 old,p=payload;start=time.perf_counter();configure_metric_backend(False)
 before=source_fingerprint();cloud=ThresholdCloud(alpha=p['alpha']);g=p['metric']
 metric=LorenzMetricMode(g['orbital_radius'],cloud.a,g['m_g'],g['ellmax'])
 if cloud.a!=g['a'] or metric.provenance!=g:raise ValueError('Fresh source physics/provenance differs from original settings')
 freq,J=project_source(cloud,[old['r']],g['orbital_radius'],p['scalar_ell'],p['scalar_m'],metric,ntheta=p['angular_order'])
 if freq!=p['omega']:raise ValueError('Changed scalar frequency')
 after=source_fingerprint()
 if before!=after:raise ValueError('Production source changed while fresh calculation was running')
 oldJ=complex(*old['source']);newJ=J[0]
 return dict(pid=os.getpid(),r=old['r'],historical_source=old['source'],fresh_source=pair(newJ),difference=pair(newJ-oldJ),relative_difference=float(abs(newJ-oldJ)/abs(oldJ)),fresh_elapsed_seconds=time.perf_counter()-start,angular_nodes=p['angular_order'],metric_ellmax=g['ellmax'],metric_tensor_evaluations=metric._values.cache_info().misses,metric_cache_reused=False,source_provenance=after)
def main():
 path=FOLDER/NAME;old=json.loads(path.read_text());chosen=[min(old['samples'],key=lambda v:abs(v['r']-r)) for r in [2.,20.,80.]]
 out=FOLDER/'figure5_source_fresh_three_nodes_20260917.json'
 result=dict(status='three_node_fresh_source_running',historical_file=NAME,historical_sha256=sha(path),historical_source_provenance=old.get('source_provenance'),parameters=old['parameters'],selection=dict(target_radii=[2.,20.,80.],actual_gauss_nodes=[v['r'] for v in chosen]),samples=[],implementation_sha256=sha(Path(__file__)),limitations=['Three prespecified source nodes and only scalar22 at rp41.6; not full-grid or all-mode freshness/convergence.','No old source sample is relabelled as generated by current source.','No field/radial Green solve is recomputed by this source-only check.'])
 def save():
  tmp=out.with_suffix('.tmp');tmp.write_text(json.dumps(result,indent=2,allow_nan=False)+'\n');tmp.replace(out)
 save()
 with ProcessPoolExecutor(max_workers=3) as pool:
  pending=[pool.submit(worker,(v,old['parameters'])) for v in chosen]
  for f in as_completed(pending):
   row=f.result();result['samples'].append(row);save();print(json.dumps({k:v for k,v in row.items() if k!='source_provenance'}),flush=True)
 result['samples'].sort(key=lambda v:v['r']);result['status']='fresh_three_node_source_comparison_completed';result['max_relative_difference']=max(v['relative_difference'] for v in result['samples']);save();print(json.dumps(dict(status=result['status'],max_relative_difference=result['max_relative_difference'])),flush=True)
if __name__=='__main__':main()
